apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: red-ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
