apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: wp
  name: wp
  namespace: red-ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi

