apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: wordpress
  name: wordpress
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    io.kompose.service: wordpress
